#!/bin/bash -e

filename=${PLUGIN_FILENAME:-plan.tfout}
root_dir=${PLUGIN_ROOT_DIR:-.}
type=${PLUGIN_TYPE:-pr}
sha=${DRONE_COMMIT_SHA}
number=${DRONE_PULL_REQUEST}
title=""

export GITHUB_TOKEN=${PLUGIN_TOKEN:-$GITHUB_TOKEN}
export GITHUB_OWNER=${DRONE_REPO_OWNER}
export GITHUB_REPO=${DRONE_REPO_NAME}

if [[ -z "$number" ]]; then
  type="commit"
fi

case $type in
  commit)
    export GITHUB_COMMIT_SHA="$sha"
  ;;
  pr)
    export GITHUB_PR_ISSUE_NUMBER="$number"
  ;;
  *)
    echo "-- Supported modes:
          commit - Commit comment.
          pr - Pull Request comment.
        "
    exit 1
  ;;
esac

if [[ -n "$PLUGIN_TITLE" ]]; then
  title="### $PLUGIN_TITLE<br/>"
fi

export GITHUB_COMMENT_TYPE="$type"
export GITHUB_COMMENT=$(cat $root_dir/$filename 2>&1)
export GITHUB_COMMENT_FORMAT="${title}Output from \`terraform plan\`:<br/>\`\`\`{{.}}\`\`\`"

github-commenter